### ISSUE TITLE
Updating CLI - API rate limit exceeded

### ISSUE THREAD

**Issue by TheEadie** [TheEadie/WormsLeague#54]
### What

When trying to update the CLI you can very easily hit an exception that GitHub is rate limiting calls to it API. Without authenication each IP address can only make 60 API calls an hour.

### Proposal

- Handle these exceptions rather than bringing down the process
- Add a `worms login` command to give users more API calls if the rate limit is hit

### Details

```
Unhandled exception. Octokit.RateLimitExceededException: API rate limit exceeded for 149.13.177.34. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken)
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken)
   at Octokit.ApiConnection.GetPage[TU](Uri uri, IDictionary`2 parameters, String accepts, ApiOptions options)
   at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Octokit.ApiPagination.GetAllPages[T](Func`1 getFirstPage, Uri uri)
   at Worms.Updates.PackageManagers.GitHubReleaseRepository.GetAvailableVersions(String id)
   at Worms.Components.Updaters.GitHubReleaseUpdater.GitHubReleaseUpdater.GetAvailableVersions(Component component, GitHubReleaseUpdateConfig config)
   at Worms.Components.ComponentOperations.GetAvailableVersions(Component component)
   at Worms.Commands.Update.OnExecuteAsync(IConsole console)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Worms.Program.Main(String[] args)
{"message":"API rate limit exceeded for 149.13.177.34. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

**Comment by TheEadie** [comment]
Resolved by #58
